export const  LAY_DS_RAP = 'LAY_DS_RAP'; 
export const  LAY_DS_CUM_RAP = 'LAY_DS_CUM_RAP'; 
export const  LAY_CHI_TIET_PHIM = ' LAY_CHI_TIET_PHIM'; 

export const  LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG = 'LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG'; 
export const  LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP = 'LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP'; 

